import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { HeaderProvider } from "@/context/header-context";
import { Header } from "@/components/header";
import { Sidebar } from "@/components/sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<HeaderProvider>
					<div className="flex min-h-screen">
						<Sidebar />
						<div className="flex-1 flex flex-col min-h-screen pl-[72px]">
							<Header />
							<main className="flex-1 bg-background">
								{children}
							</main>
						</div>
					</div>
				</HeaderProvider>
			</body>
		</html>
	);
}
